package net.adiherzog.jassbot.model;

public enum MessageType {

    REQUEST_PLAYER_NAME,
    CHOOSE_PLAYER_NAME,
    DEAL_CARDS,
    REQUEST_TRUMPF,
    CHOOSE_TRUMPF,
    BROADCAST_TRUMPF,
    BROADCAST_STICH,
    BROADCAST_WINNER_TEAM,
    BROADCAST_GAME_FINISHED,
    BROADCAST_SESSION_JOINED,
    BROADCAST_TEAMS,
    PLAYED_CARDS,
    REQUEST_CARD,
    CHOOSE_CARD,
    REJECT_CARD,
    REQUEST_SESSION_CHOICE,
    CHOOSE_SESSION

}
